server:
  port: 1208
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://39.106.154.90:3306/cmfz
    url: jdbc:mysql://localhost:3306/cmfz?zeroDateTimeBehavior=convertToNull
    username: root
    password: 1221997
  mvc:
    view:
      suffix: .jsp
      prefix: /
  redis:
    host: 39.106.154.90
    port: 7000
    database: 0
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis:
  type-aliases-package: com.shun.entity
  mapper-locations: classpath:com/shun/mapper/*Mapper.xml

logging:
  level:
    com.shun.dao: debug
async:
  maxPoolSize: 50
  corePoolSize: 20
  queueCapacity: 10
